name: Main CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CTEST_OUTPUT_ON_FAILURE: 1

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        toolset: [ CLANG, GCC ]
        build_type: [ Debug, Release ]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install ninja-build tool
        uses: seanmiddleditch/gha-setup-ninja@v3

      - name: Install dependencies
        run: sudo apt install libglib2.0-dev libssl-dev libconfig-dev libjansson-dev libnice-dev libsrtp2-dev libmicrohttpd-dev libsofia-sip-ua-dev libopus-dev libogg-dev libcurl4-openssl-dev libwebsockets-dev libusrsctp-dev liblua5.4-dev -y

      - name: Create Build Environment
        run: cmake -E make_directory out/build/linux-x64-${{matrix.build_type}}-${{matrix.toolset}}/

      - name: Configure
        working-directory: out/build/linux-x64-${{matrix.build_type}}-${{matrix.toolset}}/
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{matrix.build_type}} --preset linux-x64-${{matrix.build_type}}-${{matrix.toolset}}

      - name: Build
        working-directory: out/build/linux-x64-${{matrix.build_type}}-${{matrix.toolset}}/
        run: cmake --build . --config ${{matrix.build_type}}

      - name: Test
        working-directory: out/build/linux-x64-${{matrix.build_type}}-${{matrix.toolset}}/
        run: ctest -C ${{matrix.build_type}} --output-on-failure
